image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]

variables:
    DOCKER_IMAGE_TAG: $CI_COMMIT_REF_SLUG

cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
        - node_modules/
        - dist/

stages:
    - before_build
    # - test
    - build

before_build:
    stage: before_build
    image: node:16-alpine
    script:
        - apk add --update python3 py3-pip ffmpeg
        - python3 --version
        - pip3 --version
        - ffmpeg -version
        - npm install
        - npm run build
    artifacts:
        paths:
            - dist/
    only:
        - main

build:
    stage: build
    script:
        - /kaniko/executor
          --context "${CI_PROJECT_DIR}"
          --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
          --cache=true
          --cache-dir="/cache"
          --destination "${CI_REGISTRY_IMAGE}:${DOCKER_IMAGE_TAG}"
    only:
        - main
